info:
  contact:
    name: Auckland Museum API Team
    url: http://www.aucklandmuseum.com
  description: 'This is technical documentation for the Auckland Museum API

    '
  license:
    name: Auckland Museum licence
    url: http://www.aucklandmuseum.com
  termsOfService: http://api.aucklandmuseum.com/terms/
  title: Auckland Museum API
  version: 2.0.0-oas3
  x-apisguru-categories:
  - open_data
  x-logo:
    backgroundColor: '#FFFFFF'
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_aucklandmuseum_profile_image.jpeg
  x-origin:
  - format: swagger
    url: http://api.aucklandmuseum.com/apidoc
    version: '2.0'
  x-providerName: aucklandmuseum.com
openapi: 3.0.0
paths:
  /id/media/{path}:
    get:
      description: 'Gets `media` at a given path

        '
      operationId: getIdMediaPath
      parameters:
      - description: 'The media `identifier`

          '
        in: path
        name: path
        required: true
        schema:
          type: string
      - description: 'The desired media `rendering`


          Possible values:

          * `original.jpg`

          * `original.pdf`

          * `thumbnail.jpg` (fixed with 70px)

          * `standard.jpg` (fixed width 440px and height 440px)

          * `preview.jpg` (fixed height 100px)

          '
        in: query
        name: rendering
        required: false
        schema:
          type: string
      responses:
        '200':
          description: '`media` found

            '
        '404':
          description: '`media` not found

            '
      summary: Retrieve media associated with Collections and Cenotaph subjects in
        Auckland Museum
      tags:
      - media
  /id/{identifier}:
    get:
      description: "Gets information about a `subject` identified by the `identifier`.\n\nThe
        response format depends upon the `Accept` header.\n  - `text/html` - the default
        response type. Returned data can be easily viewed in any modern Internet Browser\n
        \ - `application/ld+json` - the response will be in [JSON-LD](http://json-ld.org/)\n
        \ - `application/json` - the response will be a simple JSON Object with keys
        (predicates) and values (objects).\n"
      operationId: getIdIdentifier
      parameters:
      - description: 'The identifier path of the `subject` you''re looking for

          '
        in: path
        name: identifier
        required: true
        schema:
          type: string
      responses:
        '200':
          description: '`subject` found

            '
        '404':
          description: '`subject` not found

            '
      summary: Explore details about a given subject node
      tags:
      - subject
  /search/{index}/{operation}:
    get:
      description: "Use this endpoint to perform simple search queries for finding
        information and subjects you may be interested in\n\nSearches performed via
        this endpoint run against an [Elastic](www.elastic.co) server. This endpoint
        mirrors the Elastic search API documented [here](https://www.elastic.co/guide/en/elasticsearch/reference/1.5/search-search.html)\n\nUse
        the\n  - `collectionsonline` index to perform searches over other all\nCollections
        data\n  - `cenotaph` index to perform searches over Cenotaph data\n"
      operationId: getSearchIndexOperation
      parameters:
      - description: 'search index name

          Possible values:

          * `collectionsonline`

          * `cenotaph`

          '
        in: path
        name: index
        required: true
        schema:
          type: string
      - description: One of the supported elasticsearch operations like `_search`
          or `_suggest`
        in: path
        name: operation
        required: true
        schema:
          type: string
      - description: One of the supported elasticsearch query parameter values for
          key `q`
        in: query
        name: q
        required: false
        schema:
          type: string
      responses:
        '200':
          description: search results found
        '400':
          description: bad request
        '404':
          description: not found
      summary: Perform simple search queries over Auckland Museum Collections and
        Cenotaph data
      tags:
      - search
    post:
      description: "Searches performed via this endpoint run against an [Elastic](www.elastic.co)
        server. This endpoint mirrors the Elastic search API documented [here](https://www.elastic.co/guide/en/elasticsearch/reference/1.5/search-search.html)\n\nUse
        the\n  - `collectionsonline` index to perform searches over other all Collections
        data\n  - `cenotaph` index to perform searches over Cenotaph data\n"
      operationId: postSearchIndexOperation
      parameters:
      - description: 'search index name

          Possible values:

          * `collectionsonline`

          * `cenotaph`

          '
        in: path
        name: index
        required: true
        schema:
          type: string
      - description: One of the supported elasticsearch operations like `_search`
          or `_suggest`
        in: path
        name: operation
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              format: application/json
              type: object
        description: body
      responses:
        '200':
          description: search results found
        '400':
          description: bad request
        '404':
          description: not found
      summary: Perform complex search queries over Auckland Museum Collections and
        Cenotaph data
      tags:
      - search
  /sparql:
    get:
      description: "You can execute your [SPARQL](http://www.w3.org/TR/rdf-sparql-query/)
        queries against this endpoint.\n\nThe sparql query should be provided as the
        value of the request parameter `query`.\nSet the `Accept` header to `application/sparql-results+xml`
        to get results in XML. Set it to `application/sparql-results+json` to get
        results in JSON. \n\n**Note:** This endpoints supports [JSON-P](http://json-p.org/).
        In order to get a JSON-P response, set the query parameter `callback` to your
        preferred callback function name. The default function name is `callback()`.
        When using JSON-P, there is no need to set the `Accept` header because the
        response will always be in `application/javascript`.\n"
      operationId: getSparql
      parameters:
      - description: sparql query
        in: query
        name: query
        required: true
        schema:
          type: string
      - description: The [JSON-P](http://json-p.org/) callback parameter
        in: query
        name: callback
        required: false
        schema:
          default: callback
          type: string
      - description: Whether to get inferred results in the response
        in: query
        name: infer
        required: false
        schema:
          default: true
          type: boolean
      responses:
        '200':
          content:
            application/javascript:
              schema:
                title: json
                type: object
            application/sparql-results+json:
              schema:
                title: json
                type: object
            application/sparql-results+xml:
              schema:
                title: json
                type: object
          description: success
      summary: Auckland Museum SPARQL endpoint
      tags:
      - sparql
    post:
      description: "You can execute your [SPARQL](http://www.w3.org/TR/rdf-sparql-query/)
        queries against this endpoint.\nThe sparql query should be provided as the
        value of the request parameter `query`.\nSet the `Accept` header to `application/sparql-results+xml`
        to get results in XML. Set it to `application/sparql-results+json` to get
        results in JSON. \n"
      operationId: postSparql
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                infer:
                  default: true
                  description: Whether to get inferred results in the response
                  type: boolean
                query:
                  description: sparql query
                  type: string
              required:
              - query
              type: object
        required: true
      responses:
        '200':
          description: success
      summary: Auckland Museum SPARQL endpoint
      tags:
      - sparql
servers:
- url: https://api.aucklandmuseum.com
tags:
- description: media - images and documents
  name: media
- description: information about subjects
  name: subject
- description: search for interesting data
  name: search
- description: sparql queries
  name: sparql
